name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        directory: ['client', 'server']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ format('{0}/package-lock.json', matrix.directory) }}
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ matrix.directory }}
    - name: Build
      run: npm run build --if-present
      working-directory: ${{ matrix.directory }}
    - name: Run tests
      run: npm test
      working-directory: ${{ matrix.directory }}